### ISSUE TITLE
Setup instructions is broken

### ISSUE THREAD

**Issue by rsharifnasab** [giganticode/jemma#2]
I wanted to install workbench and required libraries, but I couldn't find `requirements.txt`. In addition to that, the `setup.py` seems empty, and running the installation command gives this error: 
```
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/home/roozbeh/apps/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/roozbeh/apps/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/roozbeh/apps/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 181, in prepare_metadata_for_build_editable
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-9jbsf1lf/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 473, in prepare_metadata_for_build_editable
          return self.prepare_metadata_for_build_wheel(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-9jbsf1lf/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 398, in prepare_metadata_for_build_wheel
          self._bubble_up_info_directory(metadata_directory, ".egg-info")
        File "/tmp/pip-build-env-9jbsf1lf/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 367, in _bubble_up_info_directory
          info_dir = self._find_info_directory(metadata_directory, suffix)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-9jbsf1lf/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 378, in _find_info_directory
          assert len(candidates) == 1, f"Multiple {suffix} directories found"
                 ^^^^^^^^^^^^^^^^^^^^
      AssertionError: Multiple .egg-info directories found
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Could anyone suggest a fix?

**Comment by JoyKrishan** [comment]
I found the issue @rsharifnasab, there is no requirements.txt file.
